---
title: "DATA Science Session 11a"
author: "Media Data Science"
date: "10/28/2019"
output: html_document
---


In our last session, we reviewed the basic set theory operations and propositions that will allow us to compute probabilities. We also defined the three axioms of probability. We determined that rather than taking a frequentist approach to probability, we use a modern axiomatic approach to probability. 

## Sample Spaces Having Equally Likely Outcomes 

When it comes to events, it is a fair assumption to think that all events are equally as likely as occuring, however that is not always the case. One scenrio could be the event of rolling a 3 with a loaded die. However, we will address how biases or external forces play a role in probability in chapter 3. For now, lets assume equally likely events. 

We define equally likely sample spaces as follows:
Suppose we have a sample space S defined as S=(1,2, 3, 4....N), then we can say...

$$
p(1)=p(2)=p(3)=...p(N)
$$


From axiom 2 and 3, it is implied that 

$$
p(i)=\frac{1}{N}\\
for \ i=1, 2, 3\\
then \ p(E)=\frac{Number \ of \ outcomes \ in \ E}{number \ of \ outcomes \ in \ S}
$$

The above expressions is stating that if we assume each event in sample space S is equally likely, then the probability of event 1 is the same as the probability of event 2 and so forth by axiom 2. Axiom 3 then says that the probability of an event is the ratio of the number ofoutcomes in an event E divided by the number of outcomes in the sample space. 

Lets now put our knowledge of combinatorics and the axioms of probability to work. 

* ex) If two dice are rolled, what is the probability that the sum of the upturned faces will
equal 7?

A good strategy is to start by defining the sample space and then working to define the event set. We are trying to find the probability of the sum of two dice being 7. Our sample space in this case is going to be the number of permutations made by rolling two dice. 

If we imagine each dice to have its own slow _ _ , then the first dice (slot 1) can have 6 possible outcomes . The second dice (slot 2) can also have 6 possible outcomes. By the generalized counting principle, our sample space has 36 possible outcomes. Of course, we can list them all out such as (1,1)(1,2)(1,3)(1,4)(1,5)(1,6)(2,1)... 

Now our event space is going to be all combinations of dice where the sum is 7. Lets list them all out. (1,6)(6,1)(2,5)(5,2)(3,4)(4,3) We have a total of 6 dice combinations where the sum is 7. We can now compute our probability of rollin two dice whose sum is 7. We know that there are 6 outcomes in the event where the sum of two dice is 7 and we know there are 36 possible outcomes as our sample space. 

$$
P(E)=\frac{Number \ of \ oucomes \ where \ sum \ of \ dice \ is \ 7}{number \ of \ outcomes \ in \ sample \ space}=\frac{6}{36}=\frac{1}{6}
$$


* ex) If 3 balls are "randomly drawn" from a bowl containing 6 white and 5 black balls, what is the probability that one of the balls is white and the other two black?

Similar to the previous problem, we want to define the elements of our event and the sample space. Lets start with the sample space. 

We want to see how many combinations of three balls could we pick from a total of 11. This is an application of combinations. We count the number of outcomes in our sample space like so :

$$
recall \ nCk=\frac{n!}{n!(n-k)!}\\
11C3=\frac{11!}{3!(11-3)!}=\frac{11 \bullet10\bullet9
\bullet8!}{3\bullet2\bullet1(8)!}=\frac{11 \bullet10\bullet9}{3\bullet2}=11\bullet5\bullet3=165
$$
There are 165 ways to pick three balls from 11. Now for our sample space. 

We need to pick 1 white out of 6 and 2 black out of 5. We use combinations plus the generalized counting principle. We look at the number of ways to pick 1 white and the number of ways to pick 2 black.

$$
Choosing \ 1 \ white: 6C1=\frac{6!}{1!(6-1)!}=\frac{6\bullet5!}{5!}=6\\
choosing \ 2 \ black: 5C2=\frac{5!}{2!(5-2)!}=\frac{5\bullet4\bullet3!}{2!3!}=5\bullet2=10\\
choosing \ 1 \ white \ 2 \ black: 6C1\bullet5C2=6\bullet10=60
$$

Hence we know there are 60 ways to choose 1 white and 2 black in addition to knowing we have 165 total possible outcomes in our sample space. The probability is computed as 

$$
P(E)=\frac{60}{165}=\frac{4}{11}
$$

An alternative way to approach this problem is if we consider the objects to be distinguishable. 

We are drawing three balls at random from a bowl that has 6 white and 5 black. If we consider three slots, where each slot represents the ball selection _ _ _, then we have 11 balls to pick from in the first slot, followed by 10 to pick in the second slot followed by 9 left to pick from in the third slot. Our sample space in this case would then be 11X10X9=990

Now our event space is defined as getting one white and two black. There are three ways to order the choices of colors.  

$$
color \ order:\{(b,b,w),(b,w,b),(w,b,b)\}=3 \ orderings\\
select \ first \ black: 5\\
select \ second \ black: 4\\
select \ 1 \ white: 6\\
event \ E=3\bullet5\bullet4\bullet6=360
$$

Hence, by considering the balls distinguishable, the probability is 

$$
P(E)=\frac{360}{990}=\frac{4}{11}
$$

We arrive at the same answer using two different combinatorical arguments. This example is a really great example that highlights the flexibility of considering the items to be ordered or unordered. 

* ex) A committee of 5 is to be selected from a group of 6 men and 9 women. If the selection is made randomly, what is the probability that the committee consists of 3 men and 2 women?

Like the previous examples, we will begin by defining our sample space. We want to select a committee of 5 people from a group of 6 men and 9 women. That means we have a total of 15 people and we want to count the number of ways we can select 5 people from a group of 15. 

$$
S=15C5=\frac{15!}{5!(15-5)!}=\frac{15!}{5!10!}=\frac{15\bullet14\bullet13\bullet12\bullet11\bullet10!}{5\bullet4\bullet3\bullet2\bullet10!}=\frac{15\bullet14\bullet13\bullet12\bullet11}{5\bullet4\bullet3\bullet2}=3\bullet7\bullet13\bullet11=3003
$$
Our sample space has a total of 3003 ways to select 5 people from a group of 15. Now we define our event space. 

We want to select 3 men from 6 and 2 women from 9. We can use a ordered or unordered argument, however the unordered argument is simpler. 

$$
pick \ 3 \ men: 6C3=\frac{6!}{3!(6-3)!}=\frac{6\bullet5\bullet4\bullet3!}{3\bullet2\bullet3!}=5\bullet4=20\\
pick \ 2 \ women: 9C2=\frac{9!}{2!(9-2)!}=\frac{9\bullet8\bullet7!}{2\bullet1\bullet7!}=9*4=36\\
pick \ 3 \ men \ and \ 2 \ women=(6C3)(9C2)=20\bullet36=720
$$

We found that there are 720 ways to select 3 men and 2 women. We can now define the probability for that event. 

$$
P(E)=\frac{720}{3003}=\frac{240}{1001}
$$

* ex) A total of 36 members of a club play tennis, 28 play squash, and 18 play badminton. Furthermore, 22 of the members play both tennis and squash, 12 play both tennis
and badminton, 9 play both squash and badminton, and 4 play all three sports. How
many members of this club play at least one of three sports?


We are given information regarding the number of people playing a sport. What makes this problem tricky is that we are also given the number of people that play multiple sports. We need to consider how intersections could play a role in this problem. Lets organize the information we are given .

$$
36 \ people \ play \ tennis\\
28 \ people \ play \ squash\\
18 \ people \ play \ badminton\\
22 \ people \ play \ both \ tennis \ and \ squash\\
12 \ people \ play \ both \ tennis \ and \ badminton\\
9 \ people \ play \ both \ squash \ and \ badminton\\
4 \ people \ play  \ tennis \ and \ squash \ and \ badminton\\
$$

 We can't tell how many people there are in total at the moment so lets assume that this club has N people. This will be our sample space for now. 
 
 We want to define the event where people play at least one of the three sports, meaning they play tennis or squash or badminton. The fact that I used "or" should be a clue that we want to find the probability of the union of the events where people play tennis , squash, and badminton. Hence we want to find the following probability:
 
$$
Event \ A: people \ who \ play \ tennis \\
Event \ B: people \ who \ play \ squash \\
Event \ C: people \ who \ play \ badminton \\
p(A \cup B\cup C)
$$

If we recall our previous lesson, we examined a proposition that modeled the relationship between unions and intersections as follows:

$$
P(A \cup B) = P(A)+P(B)-P(A \cap B)
$$

We can extend this proposition to three events as shown below: 
https://math.stackexchange.com/questions/3088774/probability-inclusion-exclusion-with-3-events


$$
p(A \cup B\cup C)= p(A)+p(B)+p(C)-p(A \cap B)-p(A \cup C)-p(B \cap C)+p(A \cap B \cap C)
$$

Lets use the information we are given to determine how many terms we can fill in:

$$
36 \ people \ play \ tennis: P(A)=\frac{36}{N}\\
28 \ people \ play \ squash: P(B)=\frac{28}{N}\\
18 \ people \ play \ badminton: P(C)=\frac{18}{N}\\
22 \ people \ play \ both \ tennis \ and \ squash: P(A \cap B)=\frac{22}{N}\\
12 \ people \ play \ both \ tennis \ and \ badminton: P(A \cap C)=\frac{12}{N} \\
9 \ people \ play \ both \ squash \ and \ badminton: P(B \cap C)=\frac{9}{N} \\
4 \ people \ play  \ tennis \ and \ squash \ and \ badminton: P(A \cup B \cup C)=\frac{4}{N}\\
p(A \cup B\cup C)= p(A)+p(B)+p(C)-p(A \cap B)-p(A \cup C)-p(B \cap C)+p(A \cap B \cap C)\\
p(A \cup B\cup C)=\frac{1}{N}(36+28+18-22-12-9-4)\\
p(A \cup B\cup C)=\frac{1}{N}(43)\\
p(A \cup B\cup C)=\frac{43}{N}
$$

We will omitt the more niche and theoretical portions in the remainder of the chapter but you are more than welcome to read them. The homework problems are at the end of the chapter. 

## Homework 

* Problems Section (Page 50): 1, 3, 7, 8, 9, 11, 19,28


* Self Test section (page 56): 1, 2, 7, 12














