---
title: "Data Science Session 8a"
author: "Media Data Science"
date: "July 29, 2019"
output: html_document
---

# Intro to Trig Continued 2

We will skip graphing tangent, secant, cosecant, and cotangent but I leave this link for your own reading 
https://www.sparknotes.com/math/trigonometry/graphs/section2/
Part of the reason we will gloss over graphing these functions will be because we are just focusing on the fundamentals. 

Today, we are going to go over trigonometric proofs. These problems will test your ability to re-write trig expressions from one form to another and prove equalities based on how these expressions can be re-written. 

The following document contains a comprehensive list of trigonometric identities and formulas 
https://www2.clarku.edu/faculty/djoyce/trig/identities.html

The readings, practice problems, and HW problems for this section can be found here 
https://github.com/vindication09/Data-Science-Mathematics/blob/master/Trig%20Identities%20Handout.pdf


The general idea for these problems is that you will prove that the right hand side is equal to the left hand side or vice versa. We are not trying to solve an equation. We are trying to validate an identity by using what we know about trig identities. 

Ex) 

Verify the identity 

$$
(csc\theta+cot\theta)(csc\theta-cot\theta)=1
$$

Lets examine what the best strategy here is. There is clearly nothing we can do with the right hand side so we will want to focus our attention to the left hand side. The way the left hand side is set up, it seems that we can multiply this expression out using F.O.I.L and then simplify as much as we can.

$$
(csc^{2}\theta-csc\theta cot\theta + csc\theta cot\theta-cot^{2}\theta)=1\\
csc^{2}\theta-cot^{2}=1
$$
We are now at the point where we need to make a determination on what identity can be seen in the left hand expression. Refer to the complete list of trig identities in the link provided earlier. From the sheet, we identify the following identity. It is not quite what we need though so lets do some manipulation on the identity. Lets leave th 1 on the right hand side and move the cot to the other side by subtracting. 

$$
1+cot^{2}\theta =csc^{2}\theta\\
1=csc^{2}\theta - cot^{2}\theta

$$

Now lets validate our original identity 

$$
csc^{2}\theta-cot^{2}=1\\
1=1
$$

Lets Try a different example. Validate the following identity

$$
\frac{sec\theta - cos\theta}{sec\theta + cos\theta }=\frac{sin^{2}\theta}{1+cos^{2}\theta}
$$
This problems looks a tad more complex than the previous one. We will need to determine what the best strategy is. The right hand side is aready in terms of sin and cos so it is the less complicated of the expressions. The general rule of thumb is that you want to focus on manipulating to "harder" looking expression. In this case the more complex looking expression is the left hand side. It should be noted that if you have trouble choosing what side to work with, you'll most likely hit a wall if you pick the wrong side. 

Lets begin to re-write the left hand side. I will want to express everything as either sin or cos, so I will use the reciprocal identity for sec

$$
\frac{\frac{1}{cos\theta} - cos\theta}{\frac{1}{cos\theta} + cos\theta }=\frac{sin^{2}\theta}{1+cos^{2}\theta}
$$

I end up creating a complex fraction on the left hand side, however I can clear the complex fractions by multiplying the top and bottom of the left hand side by cos. We do not need to multiply the right hand side because we are simply clearning complex fractions which as isolated in the left hand side. 

$$
\frac{(cos\theta)(\frac{1}{cos\theta} - cos\theta)}{(cos\theta)(\frac{1}{cos\theta} + cos\theta )}=\frac{sin^{2}\theta}{1+cos^{2}\theta}\\
\frac{1-cos^{2}\theta}{1+cos^{2}\theta}=\frac{sin^{2}\theta}{1+cos^{2}\theta}
$$

Lets see if we can identify an identity from our list of identities. Recall the trigonometric identity. We will also need to re-write the trigonometric identity to look like the numerator on the left hand side 

$$
sin^{2}\theta + cos^{2}\theta = 1\\
sin^{2}\theta=1=cos^{2}\theta
$$

We have what we need to verify the identity 

$$
\frac{1-cos^{2}\theta}{1+cos^{2}\theta}=\frac{sin^{2}\theta}{1+cos^{2}\theta}\\
\frac{sin^{2}\theta}{1+cos^{2}\theta}=\frac{sin^{2}\theta}{1+cos^{2}\theta}
$$

Not so bad, huh? Lets try one more. Verify the folling identity. 

$$
cos(x+y)+cos(x-y)=2cosxcosy
$$

It looks like we will needto focus more on the left hand side of the equation. The terms in the left hand side look similar to the sum difference identities. Lets replace each term in the left hand side with its sum difference form. Once we re-write the terms on the left hand side with their sum difference form, then we can proceed to simplify. 

$$
(cosxcosy-sinxsiny)+(cosxcosy+sinxsiny)=2cosxcosy\\
cosxcosy-sinxsiny+cosxcosy+sinxsiny=2cosxcosy\\
cosxcosy+cosxcosy=2cosxcosy\\
2cosxcosy=2cosxcosy
$$


#Whats to come

We did a crash course of the most fundamental topics in a standard pre-calculus curriculum. Going forward, we want to be able to apply our learnings to probability, calculus, and linear algebra. 

This is the sequence of items we are going to look at going down the pipeline. 

##Intro to Probability and Statistics
##Intro to matrix algebra 
##Intro to 1D calculus 





